"""
Airline code mappings for enriching aircraft data.
Maps ICAO airline codes (first 3 letters of callsign) to airline names.
"""

# ICAO airline codes to airline names mapping
AIRLINE_CODES = {
    "AAL": "American Airlines",
    "AAR": "Asiana Airlines", 
    "ABR": "ASL Airlines Belgium",
    "ACA": "Air Canada",
    "ACE": "Alaska Central Express",
    "ADR": "Adria Airways",
    "AEA": "Air Europa",
    "AFL": "Aeroflot",
    "AFR": "Air France",
    "AHY": "Azerbaijan Airlines",
    "AIC": "Air India",
    "AJX": "Air Japan",
    "AKL": "Air KBZ",
    "ALK": "SriLankan Airlines",
    "ANA": "All Nippon Airways",
    "ANZ": "Air New Zealand",
    "APG": "Apollo Airways",
    "ARG": "Aerolíneas Argentinas",
    "ASA": "Alaska Airlines",
    "AUA": "Austrian Airlines",
    "AVA": "Avianca",
    "AWE": "US Airways",
    "AXB": "Air India Express",
    "AXM": "AirAsia India",
    "AZA": "Alitalia",
    "BAW": "British Airways",
    "BEL": "Brussels Airlines",
    "BER": "Air Berlin",
    "BOX": "Blue Air",
    "BTI": "Air Baltic",
    "BVN": "Baron Aviation",
    "CAL": "China Airlines",
    "CCA": "Air China",
    "CEB": "Cebu Pacific",
    "CES": "China Eastern Airlines",
    "CHH": "Hainan Airlines",
    "CKS": "Kalitta Air",
    "CLH": "Lufthansa Cityline",
    "CLX": "Cargolux",
    "CMP": "Copa Airlines",
    "CSA": "Czech Airlines",
    "CSC": "Sichuan Airlines",
    "CSN": "China Southern Airlines",
    "CSZ": "Shenzhen Airlines",
    "CXA": "Xiamen Airlines",
    "DAL": "Delta Air Lines",
    "DLH": "Lufthansa",
    "DNV": "Scandinavian Airlines Danmark",
    "DRK": "Druk Air",
    "EAL": "Eastern Airlines",
    "EIN": "Aer Lingus",
    "EJA": "NetJets",
    "ELL": "Estonian Air",
    "ELY": "El Al",
    "ETD": "Etihad Airways",
    "ETH": "Ethiopian Airlines",
    "EWG": "Eurowings",
    "EXS": "Jet2.com",
    "EZY": "easyJet",
    "FDB": "flydubai",
    "FDX": "FedEx",
    "FIN": "Finnair",
    "FJI": "Fiji Airways",
    "FLI": "Atlantic Airways",
    "GAL": "Garuda Indonesia",
    "GEC": "Lufthansa Cargo",
    "GFA": "Gulf Air",
    "GIA": "Garuda Indonesia",
    "GTI": "Atlas Air",
    "GWI": "Germanwings",
    "HAL": "Hawaiian Airlines",
    "IBE": "Iberia",
    "ICE": "Icelandair",
    "IGO": "IndiGo",
    "JAI": "Jet Airways",
    "JAL": "Japan Airlines",
    "JBU": "JetBlue Airways",
    "JZA": "Jazz Aviation",
    "KAL": "Korean Air",
    "KLM": "KLM",
    "LAN": "LATAM Airlines",
    "LOF": "Trans States Airlines",
    "LOT": "LOT Polish Airlines",
    "LTU": "LTU International",
    "LXJ": "Flexjet",
    "MAS": "Malaysia Airlines",
    "MSR": "EgyptAir",
    "NKS": "Spirit Airlines",
    "NWA": "Northwest Airlines",
    "OAL": "Olympic Air",
    "PAL": "Philippine Airlines",
    "PGT": "Pegasus Airlines",
    "QFA": "Qantas",
    "QTR": "Qatar Airways",
    "RJA": "Royal Jordanian",
    "ROT": "TAROM",
    "RPA": "Republic Airways",
    "RYR": "Ryanair",
    "SAA": "South African Airways",
    "SAS": "Scandinavian Airlines",
    "SAW": "Saudia",
    "SBI": "S7 Airlines",
    "SDM": "Rossiya Airlines",
    "SEJ": "SpiceJet",
    "SIA": "Singapore Airlines",
    "SKW": "SkyWest Airlines",
    "SLI": "Servicios de Logística Integrada",
    "SWA": "Southwest Airlines",
    "SWR": "Swiss International Air Lines",
    "TAM": "TAM Airlines",
    "TAP": "TAP Air Portugal",
    "TAR": "Tunisair",
    "THA": "Thai Airways",
    "THY": "Turkish Airlines",
    "TRA": "Transavia",
    "TSC": "Air Transat",
    "TUI": "TUI Airways",
    "TVF": "Transavia France",
    "TWI": "Tailwind Airlines",
    "UAL": "United Airlines",
    "UPS": "UPS Airlines",
    "VIR": "Virgin Atlantic",
    "VLG": "Vueling",
    "VOI": "Volaris",
    "VRD": "Virgin America",
    "WJA": "WestJet",
    "WZZ": "Wizz Air"
}

def get_airline_from_callsign(callsign: str) -> str:
    """
    Get airline name from callsign using ICAO airline code.
    
    Args:
        callsign: Aircraft callsign (e.g., "TAR954")
        
    Returns:
        Airline name or None if not found
    """
    if not callsign or len(callsign) < 3:
        return None
        
    # Extract first 3 letters as airline code
    airline_code = callsign[:3].upper()
    
    return AIRLINE_CODES.get(airline_code)